### ISSUE TITLE
HTML layouts broken?

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-un#43] opened 2020-03-24 10:23 UTC
<img width="1257" alt="Screen Shot 2020-03-24 at 6 22 11 PM" src="https://user-images.githubusercontent.com/11865/77414758-7b894000-6dfc-11ea-9718-816563828db5.png">

@w00lf could you have a look? Thanks.

**Comment by w00lf** [comment] 2020-03-25 06:45
Hi there, @ronaldtse , can you send me the adoc you are using? On what browser and os is it? Cannot reproduce on my computer

Firefox:
![image](https://user-images.githubusercontent.com/1158036/77509031-175a9080-6e7d-11ea-9694-8eb2d75c7351.png)
Chrome:
![image](https://user-images.githubusercontent.com/1158036/77509117-3a854000-6e7d-11ea-8811-f30e69120842.png)
Safari:
![image](https://user-images.githubusercontent.com/1158036/77509139-45d86b80-6e7d-11ea-8699-4b32b3c81ac7.png)

**Comment by w00lf** [comment] 2020-03-25 06:45
Also, can you also send me your Gemfile.lock, thanks

**Comment by ronaldtse** [comment] 2020-03-25 07:15
@w00lf this is from `mn-samples-un`. Let's not use the RFC 6350 document example anymore because it is incorrect for this purpose. (RFC 6350 is meant for IETF only...)

**Comment by ronaldtse** [comment] 2020-03-25 07:16
This particular document is: https://github.com/metanorma/mn-samples-un/blob/master/sources/ECE_TRADE_C_CEFACT_2018_1E.adoc

**Comment by ronaldtse** [comment] 2020-03-25 07:17
@w00lf let's remove the RFC 6350 example from ALL the flavors except for IETF.

**Comment by w00lf** [comment] 2020-03-26 09:45
#47

**Comment by w00lf** [comment] 2020-04-23 08:57
Fixed in #47

**Closed by w00lf** 2020-04-23 08:57 UTC
Labels: bug
